title: <p align="center"> Hieu (Hugh) Nguyen </p>
logo: "/images/Nguyen_Hieu(Hugh)_circle.png?raw=true"
description:
  <p align="left">
  <a href="https://www.linkedin.com/in/hieuhughnguyen/">LinkedIn</a> |
  <a href="https://scholar.google.com/citations?user=iH6PLfgAAAAJ&hl=en">Google Scholar</a> |
  <a href="https://github.com/hieu-hugh-nguyen">Github</a> 
  </p>
  
  <p align="left">
  Welcome! I'm a research scientist and engineer in Machine Learning, Digital Health, and Predictive Analytics.
  
  <br><br>
  I'm getting my PhD Degree in Biomedical Engineering, Data Science track at JHU (#1 BME Program in the U.S. by US News). develop machine learning algorithms for better, more suitable, and more accurate analysis of big biomedical data. 

  </p>
  

theme: jekyll-theme-minimal
timezone: America/New_York
future: true
