title: <p align="center"> Hieu Nguyen, PhD </p>
logo: "/images/Apple_memoji2.png?raw=true"
description:
  <p align="center">
    <a href="https://scholar.google.com/citations?user=iH6PLfgAAAAJ&hl=en">Google Scholar</a> |
    <a href="https://github.com/hieu-hugh-nguyen">Personal GitHub</a>
  </p>
  
  <p align="left">
  Welcome to my page! Bridging AI research and production, I develop end-to-end solutions across multimodal healthcare data—from EHR to imaging and wearables.  <br><br>
  </p>
  

theme: jekyll-theme-minimal
timezone: America/New_York
future: true
