title: Hieu (Hugh) Nguyen # your name (or website title) here
logo: "/images/Nguyen_Hieu(Hugh).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Welcome! I'm a research scientist and engineer in Machine Learning, Digital Health, and Predictive Analytics. I'm getting my PhD degree in Biomedical Engineering at the Johns Hopkins University, Baltimore, MD, USA.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/hieuhughnguyen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
