title: Hieu (Hugh) Nguyen # your name (or website title) here
logo: "/images/Nguyen_Hieu(Hugh).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I'm a research scientist and engineer in Machine Learning, Digital Health, and Predictive Analytics.
  
  I'm getting my PhD Degree in Biomedical Engineering, Data Science track at JHU (#1 BME Program in the U.S., #10 National University by US News), working in the intersection of machine learning/AI, statistics, and medicine. I develop machine learning algorithms for better, more suitable, and more accurate analysis of big biomedical data. I'm also involved in 11 projects that employ state-of-the-art machine learning methods to answer clinical questions. I'm interested in the use of large, high-dimensional medical data in predicting disease onset, forecasting disease trajectory, personalizing therapy, and discovering novel biomarkers.

  <br><br>
  <a href="https://www.linkedin.com/in/hieuhughnguyen">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
