title: <p align="center"> Hieu (Hugh) Nguyen, PhD </p>
logo: "/images/Nguyen_Hieu(Hugh)_circle.png?raw=true"
description:
  <p align="left">
  <a href="https://www.linkedin.com/in/hieuhughnguyen/">LinkedIn</a> |
  <a href="https://scholar.google.com/citations?user=iH6PLfgAAAAJ&hl=en">Google Scholar</a> |
  <a href="https://github.com/hieu-hugh-nguyen">Github</a> 
  </p>
  
  <p align="left">
  Welcome! 
  I develop ML and statistical methods to better analyze health data, which is increasingly complex, noisy, high-dimensional, and multi-modal in nature.
  <br><br>
  I have recently obtained my PhD degree in BME, Data Science Track @JHU, with a research interest in precision medicine and digital health.
  </p>
  

theme: jekyll-theme-minimal
timezone: America/New_York
future: true
